//GALLERY
export const SHOW_NEXT_IMG = "SHOW_NEXT_IMG";
export const SHOW_PREV_IMG = "SHOW_PREV_IMG";
export const SHOW_SELECTED_IMG = "SHOW_SELECTED_IMG";
//USERS
export const LOADING_USERS = "LOADING_USERS";
export const FILTER_BY_VALUE = "FILTER_BY_VALUE";
//USER
export const GET_INFO_USER = "GET_INFO_USER";
export const CHANGE_NEW_USER = "CHANGE_NEW_USER";
export const RESET_USER_INFO = "RESET_USER_INFO";
//MODAL
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const DISABLED_BTN = "SWITCHED_BTN";
export const ACTIVE_BTN = 'ACTIVE_BTN';